site_name: WireMock Documentation
site_description: >-
  WireMock Documentation.
# FIXME: replace by production file
site_url: https://oleg-nenashev.github.io/wiremock.org/docs/
copyright: Copyright &copy; 2023 - WireMock Contributors
docs_dir: _docs
repo_url: https://github.com/wiremock/wiremock.org
repo_name: WireMock Docs on GitHub
edit_uri: edit/main/_docs/

# Build
site_dir: _site-docs

# Theme
theme:
  name: material
  custom_dir: _docs_theme
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # NOT compatible qith toc.integrate
    # - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: DM Sans
    code: Roboto Mono
  favicon: assets/images/favicon.svg
  logo: images/logos/wiremock/logo_wide.svg
  icon:
    repo: fontawesome/brands/github

extra:
  versions:
    wiremock_version: "3.3.1"
    wiremock_docker_image: "3.3.1-1"
    wiremock_baseline: "3.x"
    grpc_extension_version: 0.4.0
  social:
    - icon: fontawesome/brands/slack
      link: https://slack.wiremock.org/
      name: WireMock Community Slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wiremockorg
      name: WireMock on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wiremock/
      name: WireMock on LinkedIn
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@wiremock
      name: WireMock on Fosstodon
  analytics:
    provider: google
    # FIXME: Update when in Production
    property: G-QSLQ4RWTRP
    
extra_css:
  - assets/css/wiremock.css
  #FIXME: It will not work well due to the style collision, a refactoring is needed
  #- assets/css/main.css
  #- assets/css/main.css.map

plugins:
  - extra-sass
  - search
  - autorefs
  - macros
  - render_swagger
  # OpenGraphs
  - social:
      # custom_layouts_dir is commercial feature
  - multirepo:
      # TODO: Change to True once works
      cleanup: false
      keep_docs_dir: true
      nav_repos:
        - name: graphql-extension
          import_url: 'https://github.com/wiremock/wiremock-graphql-extension?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md, docs/* ]
        - name: grpc-extension
          import_url: 'https://github.com/wiremock/wiremock-grpc-extension?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md, docs/* ]
        - name: state-extension
          import_url: 'https://github.com/wiremock/wiremock-state-extension?branch=develop&edit_uri=/blob/develop/'
          imports: [ /README.md, docs/*  ]
        - name: otel-extension
          import_url: 'https://github.com/wiremock/wiremock-otel-extension?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md ]
        - name: faker-extension
          import_url: 'https://github.com/wiremock/wiremock-faker-extension?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md ]
          
        # Outside WireMock GitHub org
        - name: 9cookies-extension
          import_url: 'https://github.com/9cookies/wiremock-extensions?branch=master&edit_uri=/blob/master/'
          imports: [ /*.md ]
        - name: jwt-extension
          import_url: 'https://github.com/MasonM/wiremock-jwt-extension?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: cors-extension
          import_url: 'https://github.com/RichieLoco/WiremockCorsExtension?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: stub-mapping-tracker-extension
          import_url: 'https://github.com/MasonM/wiremock-stub-mapping-tracker?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: prometheus-extension
          import_url: 'https://github.com/mikeskali/wiremock-metrics?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: record-delay-extension
          import_url: 'https://github.com/anuragashok/wiremock-extension-record-delay?branch=main&edit_uri=/blob/main/'
          imports: [ /README.md ]
        - name: velocity-transformer-extension
          import_url: 'https://github.com/adamyork/wiremock-velocity-transformer?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: unused-stubs-extension
          import_url: 'https://github.com/MasonM/wiremock-unused-stubs-extension?branch=master&edit_uri=/blob/master/'
          imports: [ /README.md ]
        - name: metrics-extension
          import_url: 'https://github.com/rasklaad/wiremock-metrics?branch=master&edit_uri=/blob/master/'
          imports: [ /README.MD ]

        # System
        - name: community
          import_url: 'https://github.com/wiremock/community?branch=main&edit_uri=/blob/main/'
          imports: [ "*" ]
        - name: dotgithub
          import_url: 'https://github.com/wiremock/.github?branch=main&edit_uri=/blob/main/'
          imports: [ CONTRIBUTING.md, SECURITY.md, CODE_OF_CONDUCT.md ]
  - redirects:
      redirect_maps:
        'android.md': 'solutions/android.md'
        'go.md': 'solutions/golang.md'
        'solutions/go.md': 'solutions/golang.md'
        'graphql.md': 'solutions/graphql.md'
        'testcontainers.md': 'solutions/testcontainers.md'
        'spring-boot.md': 'solutions/spring-boot.md'
        'api.md': 'standalone/admin-api-reference.md'
        'download.md': 'download-and-installation.md'
        'tutorials.md': 'getting-started.md'
        'plain-java.md': 'java-usage.md'
        'junit-rule.md': 'junit-extensions.md'
        'junit-4.md': 'junit-extensions.md'
        'junit-5.md': 'junit-jupiter.md'
        'docker.md': 'standalone/docker.md'
        'solutions/docker.md': 'standalone/docker.md'
        'running-standalone.md': 'standalone/java-jar.md'
        'support.md': '../support'

nav:
  - Using WireMock:
    - Getting started:
        - Overview: overview.md
        - "Quick Start: API Mocking with Java and JUnit 4": quickstart/java-junit.md
        - Download and Installation: download-and-installation.md
        - WireMock Tutorials: getting-started.md
        - FAQ: faq.md
    - WireMock Standalone:
        - Running in Docker: standalone/docker.md
        - Running as a Standalone Process: standalone/java-jar.md
        - Administrating WireMock: standalone/administration.md
        - Admin REST API Specification: standalone/admin-api-reference.md
    - Java Usage:
        - JUnit 5+ Jupiter: junit-jupiter.md
        - JUnit 4 and Vintage: junit-extensions.md
        - Spring Boot: solutions/spring-boot.md
        - Plain Java: java-usage.md
        - Java configuration: configuration.md
        - Running without the HTTP Server: running-without-http-server.md
    - Stubbing & Verifying:
        - Stubbing: stubbing.md
        - Request Matching: request-matching.md
        - Response Templating: response-templating.md
        - Simulating Faults: simulating-faults.md
        - Stateful Behaviour: stateful-behaviour.md
        - Proxying: proxying.md
        - Verifying: verifying.md
    - Templating:
        - WireMock API Templates Library: mock-api-templates/README.md
        - Using Mock API Templates: mock-api-templates/usage.md
    - Record & Playback:
        - Record and Playback: record-playback.md
    - Protocols:
        - Webhooks and Callbacks: webhooks-and-callbacks.md
        - Mocking gRPC services: grpc.md
        - WireMock and GraphQL: solutions/graphql.md
        - Serving HTTPs: https.md
    - Advanced use-cases:
        - Multi-domain Mocking: multi-domain-mocking.md
        - Deploying into a servlet container: advanced/deploy-to-servlet-container.md
        - "WireMock on Java 1.7": advanced/java7.md
    - Reference:
        - Admin API: standalone/admin-api-reference.md
        - Security: dotgithub/SECURITY.md
        - WireMock API Templates Library: mock-api-templates/README.md

  - Extensions:
    - WireMock Extensions: extensions/README.md
    - Features:
      - gRPC: grpc-extension/README.md
      - GraphQL: graphql-extension/README.md
      - State: state-extension/README.md
      - Response Template Transformer: response-templating.md
      - Velocity Response Transformer: velocity-transformer-extension/README.md
      - Data Faker: faker-extension/README.md
      - Webhooks: webhooks-and-callbacks.md
      - CORS protection: cors-extension/README.md
      - JSON Web Tokens (JWT): jwt-extension/README.md
      - JSON Body Transformer: 9cookies-extension/json-body-transformer.md
      - Request Time Matcher: 9cookies-extension/request-time-matcher.md
      - Unused Stubs: unused-stubs-extension/README.md
    - Operations Extensions:
      - Metrics Extension: metrics-extension/README.MD
      - Prometheus Metrics: prometheus-extension/README.md
      - OpenTelemetry: otel-extension/README.md
    - Developer Extensions:
      - Callback Simulator: 9cookies-extension/callback-simulator.md
      - Keywords: 9cookies-extension/keywords.md
      - Stub Mapping Tracker: stub-mapping-tracker-extension/README.md
      - Record Delay Capture: record-delay-extension/README.md

  - Extending WireMock:
    - Extending WireMock: extending-wiremock.md
    - Filtering and Modifying Requests: extensibility/filtering-requests.md
    - Transforming Responses: extensibility/transforming-responses.md
    - Custom Matching: extensibility/custom-matching.md
    - Listening for Serve Events: extensibility/listening-for-serve-events.md
    - Admin API Extensions: extensibility/extending-the-admin-api.md
    - Adding Template Helpers: extensibility/adding-template-helpers.md
    - Adding Template Model Data: extensibility/adding-template-model-data.md
    - Listening for Stub Changes: extensibility/listening-for-stub-changes.md
    - Listening for Settings Changes: extensibility/listening-for-settings-changes.md
    - Mappings Loader Extensions: extensibility/adding-mappings-loader.md
    - Stub Metadata: stub-metadata.md
  
  - Community:
    - Participate in WireMock: participate.md
    - Community Slack: https://slack.wiremock.org/
    - Contributor Guide: community/contributing/README.md 
    - Hacktoberfest 2023: dotgithub/CONTRIBUTING.md
    - Creating Extensions: extending-wiremock.md
    - Governance: community/governance/README.md
    - Code of Conduct: dotgithub/CODE_OF_CONDUCT.md

  - Resources:
    - Community Resources: resources/README.md
    - Community Slack: https://slack.wiremock.org/
    - Events:
        Overview: community/events/README.md
        Hacktoberfest: community/events/hacktoberfest/README.md
        Archives: https://www.youtube.com/@WireMockChannel/playlists
        Speaking: community/contributing/README.md#help-to-spread-the-word
    - WireMock Support: dotgithub/SUPPORT.md
    - Reporting Security Issues: dotgithub/SECURITY.md
    - External Resources: resources/external.md

 # Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: '#'
